name: Rust Build

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'Makefile'
      - '.github/workflows/build.yaml'

jobs:
  # Split up the jobs by OS, as each OS has its
  # own peculiarities for constructing the build environment.

  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      # Boilerplate
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: rustup update

      # Ubuntu setup
      - name: Apt Setup
        run: sudo apt-get update

      - name: Install dependent libraries
        run: sudo apt-get install -y libseccomp-dev

      # Common Build
      - name: Build
        run: make


  windows-clang-build:
    runs-on: windows-latest
    steps:
      # Boilerplate
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: rustup update
      
      #- name: Upgrade Clang
      #  uses: egor-tensin/setup-clang@v2
      #  with:
      #    platform: x64

      # Common Build
      - name: Build
        run: make test-debug build-default CC=clang


  #windows-gcc-build:
  #  runs-on: windows-latest
  #  steps:
  #    # Boilerplate
  #    - name: Checkout code
  #      uses: actions/checkout@v2
  #
  #    - name: Set up Rust
  #      run: rustup update
  #    
  #    # Common Build
  #    - name: Build
  #      run: make test-debug build-default
